### ISSUE TITLE
train.csv and test.csv is missing in the "Dataset" folder

### ISSUE THREAD

**Issue by dshlai** [IKMLab/rnn_tutorial#1]
Hi, the train.csv and test.csv is missing in the 'Dataset' folder. Can you give direction on where to obtain the datasets? Thanks

**Comment by zake7749** [comment]
You can download the dataset from the kaggle competition, [Toxic Comment Classification Challenge](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/data).

**Comment by dshlai** [comment]
Yeah, I got it. Thank you.
